# Generated by Django 4.2.1 on 2023-08-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
